name: work
on:
  push:
    branches: 
    - ok
    - cloud
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v3
     - name: Checkout code
       uses: actions/checkout@v3

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
          java-version: 17
          distribution: 'temurin'
     #finally build your app with the latest command
     - name: Build and test with Maven
       run: mvn clean verify

