name: Push images
on:
  #Runs when 'Run tests' succeeds and runs on main
  workflow_run:
    workflows:
      - Run tests
    types:
      - completed
    branches:
      - main

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Push the images to Docker Hub
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}

      - name: Build and push image backend
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api-student-main
          # Note: tags has to be all lower-case
          tags:  ${{secrets.USER}}/tp1-backend
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image database
        uses: docker/build-push-action@v5
        with:
          context: ./Database
          tags:  ${{secrets.USER}}/tp1-database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push image frontend
        uses: docker/build-push-action@v5
        with:
          context: ./HTTPServer
          tags:  ${{secrets.USER}}/tp1-httpd
          push: ${{ github.ref == 'refs/heads/main' }}
